update all components then add media query
chandrahmani/hello-travel pull request #6
Opened 2023-03-04 05:22 UTC by chandrahmani

2023-03-04 17:23 UTC, hidaytrahman reviewed
Minor adjustment needed

2023-03-04 17:23 UTC, hidaytrahman commented on index.html
> +  <title> Hello Treval </title>
```suggestion
  <title>Hello Travel India </title>
```

2023-03-04 17:23 UTC, hidaytrahman commented on index.html
> +  <title> Hello Treval </title>
Spelling mistake

2023-03-04 17:23 UTC, hidaytrahman commented on src/components/adventur/Advent.css
>  .bttn {
it should be `btn` not `bttn`

2023-03-04 17:23 UTC, hidaytrahman commented on src/components/adventur/Adventur.jsx
> +                            <a href='https://www.hellotravelindia.in/'>webtechpie.com</a>
Put webtechpie.com link

2023-03-09 10:06 UTC, hidaytrahman commented
@chandrahmani -  Whats is the update?

2023-03-10 17:02 UTC, hidaytrahman commented on index.html
> +  <title> Hello Treval </title>
its not solved

2023-03-10 17:23 UTC, chandrahmani commented on src/components/adventur/Adventur.jsx
> +                            <a href='https://www.hellotravelindia.in/'>webtechpie.com</a>
update link add webtechpie.com link

2023-03-10 17:29 UTC, chandrahmani commented on src/components/adventur/Advent.css
>  .bttn {
--update className btn

2023-03-10 17:31 UTC, hidaytrahman commented on src/components/adventur/Advent.css
>  .bttn {
you don't need to confirm if you have done the changes

2023-03-10 19:25 UTC, hidaytrahman requested changes
Try to resolve all the comments

2023-03-10 19:25 UTC, hidaytrahman commented on package.json
> +    "@phosphor-icons/core": "^1.4.5",
why you have added `@phosphor-icons/core`

2023-03-10 19:25 UTC, hidaytrahman commented on src/App.jsx
> +import Adventur from './components/adventur/Adventur';
wrong spelling `Adventur`. for all of this words

2023-03-10 19:25 UTC, hidaytrahman commented on src/App.jsx
> +import Servic from './components/service/Servic';
wrong spell `Servic`

 use this `Service`

2023-03-10 19:25 UTC, hidaytrahman commented on src/App.jsx
> +            <Route path='travel' element={<TravelDtl />} />
TravelDetails

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/adventur/Advent.css
> +.advent-section {
????? correct it

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/adventur/Advent.css
>  .anchor {
link or a

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/adventur/Advent.css
>  .txts {
what it does, show me the screenshot?

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/adventur/Advent.css
> +.text-wrp {
wrp? wrapper

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/adventur/Advent.css
> +    .num-wrp {
num ???

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/adventur/Adventur.jsx
> +                                    <p c>Welcome to your 'Glorious Kashmir' tour! Arrive into Airport in Srinagar. You will be met and transferred to your houseboat in Srinagar. When we think of Kash
what is c?

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/adventur/Adventur.jsx
> +                            <a href='#' ht className='num'>
??? ht

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/core/navbar/Button.jsx
> +const Size = ['btn--medium', 'btn--large']
why  this is an array?

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/core/navbar/Button.jsx
> +    const checkButtonStylev = Style.includes(buttonStyle)
what is `checkButtonStylev` ?

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/core/navbar/Navbar.jsx
> +// import img from './travel.png'
🤖

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/core/navbar/Navbar.jsx
> +    return (<>
indent or formatting

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/core/navbar/Navbar.jsx
> +                        <Link to="/adventur" className="nav-links" onClick={closeMobileMenu}>
??

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/header/Header.css
> +.phn-num {
.phn?

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/header/Header.css
> +.header-flex {
why header flex?

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/header/Header.jsx
> +        console.log(data)
🤖

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/service/Servic.jsx
> +                    <div className='section-conatiner' >
conatiner??

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/service/Servic.jsx
> +                        <div className='imgs'>
imgg ?

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/travelDtl/TravelDtl.jsx
> +                            <div className="grid-container" key={index}>
key  will always have the unique id not the index if we have option to add ID

2023-03-10 19:25 UTC, hidaytrahman commented on src/components/travelDtl/TravelDtl.jsx
> +                                    <div className="info-wrappers">
singular?

2023-03-11 03:52 UTC, chandrahmani commented on src/App.jsx
> +import Adventur from './components/adventur/Adventur';
👍

2023-03-11 03:52 UTC, chandrahmani commented on src/App.jsx
> +import Servic from './components/service/Servic';
👍

2023-03-11 03:58 UTC, chandrahmani commented on src/components/adventur/Adventur.jsx
> +                                    <p c>Welcome to your 'Glorious Kashmir' tour! Arrive into Airport in Srinagar. You will be met and transferred to your houseboat in Srinagar. When we think of Kash
added by mistake

2023-03-11 03:58 UTC, chandrahmani commented on src/components/adventur/Adventur.jsx
> +                            <a href='#' ht className='num'>
added by mistake

2023-03-11 04:11 UTC, chandrahmani commented on src/components/core/navbar/Navbar.jsx
> +// import img from './travel.png'
👍

2023-03-11 05:06 UTC, hidaytrahman requested changes

2023-03-11 05:06 UTC, hidaytrahman commented on src/components/adventur/Advencher.css
> +.advencher-container {
adventure

2023-03-11 05:06 UTC, hidaytrahman commented on src/components/header/Header.css
> +    .info-conatiner {
??? spelling

2023-03-11 05:06 UTC, hidaytrahman commented on src/components/travelDtl/TravelDetails.jsx
> +            console.log(data)
🤖

2023-03-11 05:06 UTC, hidaytrahman commented on src/components/travelDtl/TravelDetails.jsx
> +                                        <button className="btns">Get Quote</button>
btns?

2023-03-11 05:43 UTC, chandrahmani commented on src/components/service/Servic.jsx
> +                    <div className='section-conatiner' >
👍

2023-03-11 06:13 UTC, hidaytrahman approved these changes

2023-03-11 06:15 UTC, merged